import type { ImagePlaceholder } from './placeholder-images';
import { PlaceHolderImages } from './placeholder-images';

export type Level = {
  id: number;
  topicId: number;
  topicTitle: string;
  isFirstInTopic: boolean;
  title: string;
  description: string;
  challenge: string;
  starterCode: string;
  solution: string;
  image: ImagePlaceholder;
  expectedOutput: string;
  xp: number;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  hints: string[];
};

const findImage = (id: string) => {
  const img = PlaceHolderImages.find((img) => img.id === id);
  if (!img) throw new Error(`Image with id ${id} not found`);
  return img;
};

export const levels: Level[] = [
  // Topic 1: The Journey Begins
  {
    id: 1,
    topicId: 1,
    topicTitle: "The Journey Begins",
    isFirstInTopic: true,
    title: "A Classic Greeting",
    description: "Your first task is to introduce yourself to the world by printing a message.",
    challenge: "Use the `print()` function to output the text 'Hello, World!'",
    starterCode: "# Your code here\n",
    solution: "print('Hello, World!')",
    image: findImage('start-village'),
    expectedOutput: "Hello, World!",
    xp: 20,
    difficulty: 'Easy',
    hints: [
      "You need to use a special function to make text appear in the console.",
      "The function you're looking for is `print()`.",
      "Try writing `print()` with the text 'Hello, World!' inside the parentheses and quotes.",
    ],
  },
  {
    id: 2,
    topicId: 1,
    topicTitle: "The Journey Begins",
    isFirstInTopic: false,
    title: "Printing Numbers",
    description: "You can print more than just text. Numbers work too!",
    challenge: "Use the `print()` function to output the number 42.",
    starterCode: "# Your code here\n",
    solution: "print(42)",
    image: findImage('start-village'),
    expectedOutput: "42",
    xp: 20,
    difficulty: 'Easy',
    hints: [
      "Use the `print()` function again.",
      "This time, put the number 42 inside the parentheses.",
      "Unlike text, numbers don't need to be surrounded by quotes.",
    ],
  },
  {
    id: 3,
    topicId: 1,
    topicTitle: "The Journey Begins",
    isFirstInTopic: false,
    title: "Simple Calculations",
    description: "The `print()` function can even show the result of math problems.",
    challenge: "Use the `print()` function to output the result of 10 + 5.",
    starterCode: "# Your code here\n",
    solution: "print(10 + 5)",
    image: findImage('start-village'),
    expectedOutput: "15",
    xp: 20,
    difficulty: 'Easy',
    hints: [
      "You can do math right inside the `print()` function.",
      "Place the expression `10 + 5` inside the parentheses of the `print()` function.",
    ],
  },
  // Topic 2: The Enchanted Forest of Variables
  {
    id: 4,
    topicId: 2,
    topicTitle: "The Enchanted Forest of Variables",
    isFirstInTopic: true,
    title: "Storing Your Name",
    description: "You must store your name in a variable to share it with the wise old owl.",
    challenge: "Create a variable named `player_name` and set its value to 'Alex'. Then, print the variable.",
    starterCode: "# Create your variable here\n\n\n# Print your variable here\n",
    solution: "player_name = 'Alex'\nprint(player_name)",
    image: findImage('enchanted-forest'),
    expectedOutput: "Alex",
    xp: 30,
    difficulty: 'Easy',
    hints: [
      "To create a variable, type the name, an equals sign (`=`), and then the value.",
      "Text values (strings) need to be in quotes, like `'Alex'`.",
      "After creating the variable, use `print(player_name)` to see its value.",
    ],
  },
  {
    id: 5,
    topicId: 2,
    topicTitle: "The Enchanted Forest of Variables",
    isFirstInTopic: false,
    title: "Storing a Score",
    description: "Variables can also store numbers.",
    challenge: "Create a variable named `score` and set its value to 100. Then, print the variable.",
    starterCode: "# Create your variable here\n\n\n# Print your variable here\n",
    solution: "score = 100\nprint(score)",
    image: findImage('enchanted-forest'),
    expectedOutput: "100",
    xp: 30,
    difficulty: 'Easy',
    hints: [
      "Creating a variable for a number is similar to text, but without the quotes.",
      "Use `score = 100`.",
      "Then print the `score` variable.",
    ],
  },
    {
    id: 6,
    topicId: 2,
    topicTitle: "The Enchanted Forest of Variables",
    isFirstInTopic: false,
    title: "Updating a Variable",
    description: "The value of a variable can be changed or updated.",
    challenge: "A variable `score` is already created with a value of 100. Add 50 to it and print the new score.",
    starterCode: "score = 100\n\n# Update and print the score\n",
    solution: "score = score + 50\nprint(score)",
    image: findImage('enchanted-forest'),
    expectedOutput: "150",
    xp: 30,
    difficulty: 'Medium',
    hints: [
      "You can use the variable itself on the right side of the `=` to update it.",
      "Try `score = score + 50`.",
      "Finally, print the updated `score`.",
    ],
  },
  // Topic 3: The Dragon's Hoard of Numbers
  {
    id: 7,
    topicId: 3,
    topicTitle: "The Dragon's Hoard of Numbers",
    isFirstInTopic: true,
    title: "Adding Gold",
    description: "The dragon has two piles of gold. Add them together.",
    challenge: "Add `120` and `55` together and print the total.",
    starterCode: "gold_coins = 120\nfound_coins = 55\n\n# Calculate and print the total\ntotal_coins = gold_coins + found_coins\nprint(total_coins)",
    solution: "gold_coins = 120\nfound_coins = 55\ntotal_coins = gold_coins + found_coins\nprint(total_coins)",
    image: findImage('dragons-cave'),
    expectedOutput: "175",
    xp: 40,
    difficulty: 'Medium',
    hints: [
      "You need to add the values of `gold_coins` and `found_coins`.",
      "Use the `+` operator.",
      "You should complete the line `total_coins = ...`"
    ],
  },
  {
    id: 8,
    topicId: 3,
    topicTitle: "The Dragon's Hoard of Numbers",
    isFirstInTopic: false,
    title: "Multiplying Gems",
    description: "The dragon wants to know the total value of its gems.",
    challenge: "There are 15 gems, and each is worth 10 gold. Calculate and print the total value.",
    starterCode: "gems = 15\ngem_value = 10\n\n# Calculate and print the total value\n",
    solution: "total_value = gems * gem_value\nprint(total_value)",
    image: findImage('dragons-cave'),
    expectedOutput: "150",
    xp: 40,
    difficulty: 'Medium',
    hints: [
      "To find the total value, you need to multiply the number of gems by their value.",
      "The multiplication operator in Python is `*`.",
      "Create a new variable and set it to `gems * gem_value`."
    ],
  },
  {
    id: 9,
    topicId: 3,
    topicTitle: "The Dragon's Hoard of Numbers",
    isFirstInTopic: false,
    title: "Splitting Treasure",
    description: "You and your friend need to split the treasure.",
    challenge: "You have 100 gold coins to split evenly between 2 people. Calculate and print how many coins each person gets.",
    starterCode: "treasure = 100\npeople = 2\n\n# Calculate and print the share\n",
    solution: "share = treasure / people\nprint(share)",
    image: findImage('dragons-cave'),
    expectedOutput: "50",
    xp: 40,
    difficulty: 'Medium',
    hints: [
      "To split something evenly, you use division.",
      "The division operator in Python is `/`.",
      "Divide `treasure` by `people` and print the result."
    ],
  },
  // Topic 4: The Conditional Bridge
  {
    id: 10,
    topicId: 4,
    topicTitle: "The Conditional Bridge",
    isFirstInTopic: true,
    title: "The Mana Check",
    description: "The bridge keeper will only let you pass if you have enough mana.",
    challenge: "You have 10 mana potions. If you have 10 or more, print 'You may pass'.",
    starterCode: "mana_potions = 10\n\n# Check if you have enough mana and print the result\n",
    solution: "if mana_potions >= 10:\n    print('You may pass')",
    image: findImage('conditional-bridge'),
    expectedOutput: "You may pass",
    xp: 50,
    difficulty: 'Medium',
    hints: [
      "This problem requires you to make a decision in your code. An `if` statement is perfect for this.",
      "Your `if` statement should check if `mana_potions` is 'greater than or equal to' 10. The operator for this is `>=`.",
      "The `print` statement must be indented under the `if` statement.",
    ],
  },
  {
    id: 11,
    topicId: 4,
    topicTitle: "The Conditional Bridge",
    isFirstInTopic: false,
    title: "The Troll's Toll",
    description: "If you don't have enough mana, the bridge keeper gives a different message.",
    challenge: "You have 5 mana potions. If you have 10 or more, print 'You may pass'. Otherwise, print 'You shall not pass!'.",
    starterCode: "mana_potions = 5\n\n# Check your mana and print the correct message\n",
    solution: "if mana_potions >= 10:\n    print('You may pass')\nelse:\n    print('You shall not pass!')",
    image: findImage('conditional-bridge'),
    expectedOutput: "You shall not pass!",
    xp: 50,
    difficulty: 'Medium',
    hints: [
      "This is like the last task, but with a second option.",
      "Use an `if` statement for the first condition and an `else` statement for the second.",
      "The code under `else` runs only if the `if` condition is false.",
    ],
  },
  {
    id: 12,
    topicId: 4,
    topicTitle: "The Conditional Bridge",
    isFirstInTopic: false,
    title: "Checking for Equality",
    description: "Sometimes you need to check if two things are exactly the same.",
    challenge: "You find a magic scroll. If the variable `scroll_type` is exactly 'fire', print 'It is a fire scroll!'.",
    starterCode: "scroll_type = 'fire'\n\n# Check if the scroll is a fire scroll\n",
    solution: "if scroll_type == 'fire':\n    print('It is a fire scroll!')",
    image: findImage('conditional-bridge'),
    expectedOutput: "It is a fire scroll!",
    xp: 50,
    difficulty: 'Medium',
    hints: [
      "To check if two values are equal, use the double equals sign `==`.",
      "A single equals sign `=` is for assigning a value to a variable.",
      "Your condition should be `scroll_type == 'fire'`.",
    ],
  },
  // Topic 5: The Spire of Loops
  {
    id: 13,
    topicId: 5,
    topicTitle: "The Spire of Loops",
    isFirstInTopic: true,
    title: "The Magic Chant",
    description: "A spell requires you to chant 'Abracadabra' 3 times.",
    challenge: "Use a for loop to print the chant 'Abracadabra' 3 times, each on a new line.",
    starterCode: "# Use a loop to print the chant 3 times\n",
    solution: "for i in range(3):\n    print('Abracadabra')",
    image: findImage('loop-spire'),
    expectedOutput: "Abracadabra\nAbracadabra\nAbracadabra",
    xp: 60,
    difficulty: 'Hard',
    hints: [
      "When you need to repeat an action a specific number of times, a `for` loop is the right tool.",
      "Python's `range()` function is often used with `for` loops. `for i in range(3):` will run the code inside it 3 times.",
      "Inside your loop, you just need a single `print()` statement for the chant.",
    ],
  },
  {
    id: 14,
    topicId: 5,
    topicTitle: "The Spire of Loops",
    isFirstInTopic: false,
    title: "Counting Steps",
    description: "As you climb the spire, you want to count your steps.",
    challenge: "Use a for loop to print the numbers 0, 1, and 2, each on a new line.",
    starterCode: "# Use a loop to count from 0 to 2\n",
    solution: "for i in range(3):\n    print(i)",
    image: findImage('loop-spire'),
    expectedOutput: "0\n1\n2",
    xp: 60,
    difficulty: 'Hard',
    hints: [
      "A `for` loop with `range(3)` creates a temporary variable (often called `i`) that holds the current count.",
      "The variable `i` will be 0, then 1, then 2.",
      "Inside the loop, just `print(i)` to see the current number.",
    ],
  },
  {
    id: 15,
    topicId: 5,
    topicTitle: "The Spire of Loops",
    isFirstInTopic: false,
    title: "Custom Counting",
    description: "The `range` function is flexible.",
    challenge: "Use a for loop to print the numbers from 1 to 3 (inclusive).",
    starterCode: "# Use a loop to count from 1 to 3\n",
    solution: "for i in range(1, 4):\n    print(i)",
    image: findImage('loop-spire'),
    expectedOutput: "1\n2\n3",
    xp: 60,
    difficulty: 'Hard',
    hints: [
      "`range()` can take two arguments: a start and an end. `range(start, end)`.",
      "The loop will stop *before* the `end` number.",
      "To include 3 in your output, you need to use `range(1, 4)`.",
    ],
  },
  // Topic 6: The Golem's Gauntlet
  {
    id: 16,
    topicId: 6,
    topicTitle: "The Golem's Gauntlet",
    isFirstInTopic: true,
    title: "Growing Power",
    description: "A golem's strength grows exponentially. Calculate its final power.",
    challenge: "Create a variable `power` set to 1. Use a `for` loop that runs 5 times to multiply `power` by 2 each time. Finally, print the `power`.",
    starterCode: "power = 1\n\n# Your code here to update and print the power\n",
    solution: "power = 1\nfor i in range(5):\n    power = power * 2\nprint(power)",
    image: findImage('golem-gauntlet'),
    expectedOutput: "32",
    xp: 70,
    difficulty: 'Hard',
    hints: [
      "You'll need a `for` loop that repeats 5 times. `for i in range(5):` is the way to do it.",
      "Inside the loop, you need to update the `power` variable.",
      "The update operation should be `power = power * 2`.",
      "Make sure to print the final value of `power` *after* the loop has finished."
    ],
  },
  {
    id: 17,
    topicId: 6,
    topicTitle: "The Golem's Gauntlet",
    isFirstInTopic: false,
    title: "The Golem's Riddle",
    description: "A golem speaks in riddles. You must mimic its logic to pass.",
    challenge: "Loop from 1 to 10. If the number is less than 5, print 'low'. If it is greater than 5, print 'high'. If it is exactly 5, print 'middle'.",
    starterCode: "# Your code here\n",
    solution: "for i in range(1, 11):\n    if i < 5:\n        print('low')\n    else:\n        if i > 5:\n            print('high')\n        else:\n            print('middle')",
    image: findImage('golem-gauntlet'),
    expectedOutput: "low\nlow\nlow\nlow\nmiddle\nhigh\nhigh\nhigh\nhigh\nhigh",
    xp: 70,
    difficulty: 'Hard',
    hints: [
      "You need a `for` loop that goes from 1 up to (and including) 10. `range(1, 11)` is what you need.",
      "Inside the loop, you need to check the value of the loop variable.",
      "Use an `if/else` structure. The first `if` can check `i < 5`.",
      "In the `else` block, you'll need another, nested `if/else` to tell the difference between `i > 5` and `i == 5`."
    ],
  },
  {
    id: 18,
    topicId: 6,
    topicTitle: "The Golem's Gauntlet",
    isFirstInTopic: false,
    title: "Starry Night",
    description: "Reproduce the pattern of stars you see in the night sky above the golem.",
    challenge: "Use a loop to print a growing string of stars. The first line should have one star, the second two, and so on, up to 5 stars.",
    starterCode: "# Your code here\n",
    solution: "stars = ''\nfor i in range(5):\n    stars = stars + '*'\n    print(stars)",
    image: findImage('golem-gauntlet'),
    expectedOutput: "*\n**\n***\n****\n*****",
    xp: 70,
    difficulty: 'Hard',
    hints: [
      "You'll need a variable to hold the string of stars, initialized to an empty string `''` before the loop.",
      "Use a `for` loop that runs 5 times.",
      "Inside the loop, add one more star to your string variable: `stars = stars + '*'`.",
      "Also inside the loop, print the `stars` variable in each iteration.",
    ],
  },
];
