import type { ImagePlaceholder } from './placeholder-images';
import { PlaceHolderImages } from './placeholder-images';

export type Level = {
  id: number;
  topicId: number;
  topicTitle: string;
  isFirstInTopic: boolean;
  title: string;
  description: string;
  challenge: string;
  starterCode: string;
  solution: string;
  image: ImagePlaceholder;
  expectedOutput: string;
  xp: number;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  hints: string[];
};

const findImage = (id: string) => {
  const img = PlaceHolderImages.find((img) => img.id === id);
  if (!img) throw new Error(`Image with id ${id} not found`);
  return img;
};

export const levels: Level[] = [
  // Topic 1: The Journey Begins (3 tasks)
  {
    id: 1,
    topicId: 1,
    topicTitle: "The Journey Begins",
    isFirstInTopic: true,
    title: "Task 1: A Classic Greeting",
    description: "Start your adventure by learning the ancient art of displaying messages.",
    challenge: "Use the `print()` function to output the text 'Hello, World!'",
    starterCode: "# Your code here\n",
    solution: "print('Hello, World!')",
    image: findImage('start-village'),
    expectedOutput: "Hello, World!",
    xp: 10,
    difficulty: 'Easy',
    hints: [
      "You need to use a special function to make text appear.",
      "The function you're looking for is `print()`.",
      "Place the text 'Hello, World!' inside the parentheses, wrapped in quotes.",
    ],
  },
  {
    id: 2,
    topicId: 1,
    topicTitle: "The Journey Begins",
    isFirstInTopic: false,
    title: "Task 2: A New Message",
    description: "Practice your new skill by sending a different message to the world.",
    challenge: "Use the `print()` function to output the text 'The adventure begins!'",
    starterCode: "# Your code here\n",
    solution: "print('The adventure begins!')",
    image: findImage('start-village'),
    expectedOutput: "The adventure begins!",
    xp: 15,
    difficulty: 'Easy',
    hints: [
        "Just like the last task, you'll use the `print()` function.",
        "Remember to put your text inside single or double quotes.",
        "The full line should be `print('The adventure begins!')`."
    ],
  },
  {
    id: 3,
    topicId: 1,
    topicTitle: "The Journey Begins",
    isFirstInTopic: false,
    title: "Task 3: Printing Numbers",
    description: "The `print()` function isn't just for text. It can handle numbers too.",
    challenge: "Use the `print()` function to output the number `100`.",
    starterCode: "# Your code here\n",
    solution: "print(100)",
    image: findImage('start-village'),
    expectedOutput: "100",
    xp: 20,
    difficulty: 'Easy',
    hints: [
        "You'll use the `print()` function again.",
        "When printing numbers, you don't need to use quotes.",
        "Simply place the number `100` inside the parentheses."
    ],
  },
  // Topic 2: Forest of Variables (3 tasks)
  {
    id: 4,
    topicId: 2,
    topicTitle: "Forest of Variables",
    isFirstInTopic: true,
    title: "Task 1: Storing Your Name",
    description: "Learn to store information in variables, like a name in a scroll.",
    challenge: "Create a variable named `player_name` and set its value to 'Alex'. Then, print the variable.",
    starterCode: "# Create your variable here\n\n# Print your variable here\n",
    solution: "player_name = 'Alex'\nprint(player_name)",
    image: findImage('enchanted-forest'),
    expectedOutput: "Alex",
    xp: 20,
    difficulty: 'Easy',
    hints: [
      "To create a variable, type the name, an equals sign (`=`), and then the value.",
      "Text values (strings) need to be in quotes, like `'Alex'`.",
      "After creating the variable, use `print(player_name)` to see its value.",
    ],
  },
  {
    id: 5,
    topicId: 2,
    topicTitle: "Forest of Variables",
    isFirstInTopic: false,
    title: "Task 2: Tracking Health",
    description: "Variables can also hold numbers, like your health points.",
    challenge: "Create a variable named `player_health` and set it to `100`. Then, print the variable.",
    starterCode: "# Your code here\n",
    solution: "player_health = 100\nprint(player_health)",
    image: findImage('enchanted-forest'),
    expectedOutput: "100",
    xp: 25,
    difficulty: 'Easy',
    hints: [
      "Creating a numeric variable is like creating a text variable.",
      "This time, the value is `100`. Numbers don't need quotes.",
      "Use `print(player_health)` on the next line to display it.",
    ],
  },
  {
    id: 6,
    topicId: 2,
    topicTitle: "Forest of Variables",
    isFirstInTopic: false,
    title: "Task 3: A Change of Heart",
    description: "The value of a variable can be changed, or 're-assigned'.",
    challenge: "Create a variable `mood` and set it to `'happy'`. Then, on a new line, change its value to `'determined'`. Finally, print the `mood` variable.",
    starterCode: "mood = 'happy'\n# Change the mood here\n\n# Print the final mood\n",
    solution: "mood = 'happy'\nmood = 'determined'\nprint(mood)",
    image: findImage('enchanted-forest'),
    expectedOutput: "determined",
    xp: 30,
    difficulty: 'Medium',
    hints: [
      "The variable `mood` is already created for you.",
      "To change its value, simply assign a new value to it on a new line: `mood = 'determined'`.",
      "The final `print()` statement will show the newest value stored in the variable.",
    ],
  },
  // Topic 3: Dragon's Hoard of Numbers (3 tasks)
  {
    id: 7,
    topicId: 3,
    topicTitle: "Dragon's Hoard of Numbers",
    isFirstInTopic: true,
    title: "Task 1: Counting Gold",
    description: "The dragon has two piles of gold. Use the power of addition to find the total.",
    challenge: "Add `120` and `55` together and print the total.",
    starterCode: "# Calculate and print the total\n",
    solution: "print(120 + 55)",
    image: findImage('dragons-cave'),
    expectedOutput: "175",
    xp: 25,
    difficulty: 'Easy',
    hints: [
      "You can do math right inside the `print()` function.",
      "Use the `+` operator to add numbers.",
      "Place the expression `120 + 55` inside the parentheses of the `print()` function.",
    ],
  },
  {
    id: 8,
    topicId: 3,
    topicTitle: "Dragon's Hoard of Numbers",
    isFirstInTopic: false,
    title: "Task 2: Spending Gold",
    description: "You bought a new shield. Calculate your remaining gold.",
    challenge: "You have 200 gold. A shield costs 65. Subtract 65 from 200 and print the result.",
    starterCode: "# Your code here\n",
    solution: "print(200 - 65)",
    image: findImage('dragons-cave'),
    expectedOutput: "135",
    xp: 30,
    difficulty: 'Easy',
    hints: [
      "The operator for subtraction is the minus sign (`-`).",
      "You can perform the calculation directly inside `print()`.",
      "Your code should be `print(200 - 65)`."
    ],
  },
  {
    id: 9,
    topicId: 3,
    topicTitle: "Dragon's Hoard of Numbers",
    isFirstInTopic: false,
    title: "Task 3: Magical Multiplication",
    description: "An enchantment multiplies your potions. Calculate your new total.",
    challenge: "You have 8 potions. A spell triples them. Multiply 8 by 3 and print the result.",
    starterCode: "# Your code here\n",
    solution: "print(8 * 3)",
    image: findImage('dragons-cave'),
    expectedOutput: "24",
    xp: 35,
    difficulty: 'Medium',
    hints: [
      "In Python, the asterisk (`*`) is used for multiplication.",
      "Combine the numbers and the operator inside a `print()` function.",
      "Try `print(8 * 3)`."
    ],
  },
  // Topic 4: The Weaver's Loom (3 tasks)
  {
    id: 10,
    topicId: 4,
    topicTitle: "The Weaver's Loom",
    isFirstInTopic: true,
    title: "Task 1: Weaving Words",
    description: "Combine different pieces of text into a single, seamless message.",
    challenge: "Create two variables, `greeting` with value 'Hello, ' and `name` with value 'Adventurer'. Combine and print them to say 'Hello, Adventurer'.",
    starterCode: "greeting = 'Hello, '\nname = 'Adventurer'\n\n# Combine and print the variables\n",
    solution: "greeting = 'Hello, '\nname = 'Adventurer'\nprint(greeting + name)",
    image: findImage('weavers-loom'),
    expectedOutput: "Hello, Adventurer",
    xp: 30,
    difficulty: 'Easy',
    hints: [
      "The `+` operator isn't just for numbers; it can also join strings together.",
      "This process is called 'concatenation'.",
      "Use `print(greeting + name)` to combine the two variables.",
    ],
  },
  {
    id: 11,
    topicId: 4,
    topicTitle: "The Weaver's Loom",
    isFirstInTopic: false,
    title: "Task 2: A Fuller Phrase",
    description: "Weave together three separate words to form a complete thought.",
    challenge: "You are given three variables. Combine `word1`, `word2`, and `word3` to print the phrase 'Coding is fun'.",
    starterCode: "word1 = 'Coding'\nword2 = ' is '\nword3 = 'fun'\n\n# Your code here\n",
    solution: "word1 = 'Coding'\nword2 = ' is '\nword3 = 'fun'\nprint(word1 + word2 + word3)",
    image: findImage('weavers-loom'),
    expectedOutput: "Coding is fun",
    xp: 35,
    difficulty: 'Medium',
    hints: [
      "You can chain multiple `+` operators together in one line.",
      "Combine all three variables in order inside a `print()` function.",
      "The code will look like `print(word1 + word2 + word3)`."
    ],
  },
  {
    id: 12,
    topicId: 4,
    topicTitle: "The Weaver's Loom",
    isFirstInTopic: false,
    title: "Task 3: Mix and Match",
    description: "Combine a variable with a plain piece of text (a 'string literal').",
    challenge: "A variable `action` holds the word 'Attack'. Combine it with the text ' the slime!' and print the result.",
    starterCode: "action = 'Attack'\n\n# Your code here\n",
    solution: "action = 'Attack'\nprint(action + ' the slime!')",
    image: findImage('weavers-loom'),
    expectedOutput: "Attack the slime!",
    xp: 40,
    difficulty: 'Medium',
    hints: [
      "You can use `+` to add a variable and a string in quotes together.",
      "Make sure to include a space at the beginning of ' the slime!' for correct formatting.",
      "Your print statement should be `print(action + ' the slime!')`"
    ],
  },
  // Topic 5: The Conditional Bridge (3 tasks)
  {
    id: 13,
    topicId: 5,
    topicTitle: "The Conditional Bridge",
    isFirstInTopic: true,
    title: "Task 1: The Mana Check",
    description: "The bridge keeper will only let you pass if you have enough mana.",
    challenge: "You have 5 mana potions. If you have 10 or more, print 'You may pass'. Otherwise, print 'You shall not pass!'.",
    starterCode: "mana_potions = 5\n\n# Check your mana and print the correct message\n",
    solution: "mana_potions = 5\nif mana_potions >= 10:\n    print('You may pass')\nelse:\n    print('You shall not pass!')",
    image: findImage('conditional-bridge'),
    expectedOutput: "You shall not pass!",
    xp: 35,
    difficulty: 'Medium',
    hints: [
      "This requires an `if` statement to make a decision.",
      "Use `else` for the case where the `if` condition is not met.",
      "The condition should check if `mana_potions` is 'greater than or equal to' 10 (`>=`).",
    ],
  },
  {
    id: 14,
    topicId: 5,
    topicTitle: "The Conditional Bridge",
    isFirstInTopic: false,
    title: "Task 2: The Key Keeper",
    description: "You need the correct key to open the gate.",
    challenge: "You have `key_id` 7. If `key_id` is exactly `7`, print 'The gate opens.'. Otherwise, print 'Wrong key.'.",
    starterCode: "key_id = 7\n\n# Your code here\n",
    solution: "key_id = 7\nif key_id == 7:\n    print('The gate opens.')\nelse:\n    print('Wrong key.')",
    image: findImage('conditional-bridge'),
    expectedOutput: "The gate opens.",
    xp: 40,
    difficulty: 'Medium',
    hints: [
      "To check if two values are exactly equal, use a double equals sign (`==`).",
      "Your `if` condition should be `if key_id == 7:`.",
      "Don't forget the `else` block for the case where the key is wrong.",
    ],
  },
  {
    id: 15,
    topicId: 5,
    topicTitle: "The Conditional Bridge",
    isFirstInTopic: false,
    title: "Task 3: Strength Test",
    description: "A heavy door requires great strength to open.",
    challenge: "Your `strength` is 15. If your `strength` is greater than 20, print 'The door opens.'. Otherwise, print 'The door is too heavy.'.",
    starterCode: "strength = 15\n\n# Your code here\n",
    solution: "strength = 15\nif strength > 20:\n    print('The door opens.')\nelse:\n    print('The door is too heavy.')",
    image: findImage('conditional-bridge'),
    expectedOutput: "The door is too heavy.",
    xp: 45,
    difficulty: 'Medium',
    hints: [
      "The 'greater than' operator is `>`.",
      "Set up an `if/else` block to handle both possibilities.",
      "The condition `if strength > 20:` checks if your strength is high enough.",
    ],
  },
  // Topic 6: The Spire of Loops (3 tasks)
  {
    id: 16,
    topicId: 6,
    topicTitle: "The Spire of Loops",
    isFirstInTopic: true,
    title: "Task 1: The Magic Chant",
    description: "A powerful spell requires you to repeat a magic word multiple times.",
    challenge: "Use a for loop to print the chant 'Abracadabra' 3 times, each on a new line.",
    starterCode: "# Use a loop to print the chant 3 times\n",
    solution: "for i in range(3):\n    print('Abracadabra')",
    image: findImage('loop-spire'),
    expectedOutput: "Abracadabra\nAbracadabra\nAbracadabra",
    xp: 40,
    difficulty: 'Medium',
    hints: [
      "A `for` loop is used to repeat actions a specific number of times.",
      "Python's `range()` function is key. `for i in range(3):` will run the code inside it 3 times.",
      "The code that you want to repeat must be indented under the `for` loop line.",
    ],
  },
  {
    id: 17,
    topicId: 6,
    topicTitle: "The Spire of Loops",
    isFirstInTopic: false,
    title: "Task 2: Counting Steps",
    description: "As you climb the spire, count each step you take.",
    challenge: "Use a `for` loop to count from 0 to 4. In each iteration of the loop, print the current loop number.",
    starterCode: "# Your code here\n",
    solution: "for i in range(5):\n    print(i)",
    image: findImage('loop-spire'),
    expectedOutput: "0\n1\n2\n3\n4",
    xp: 45,
    difficulty: 'Medium',
    hints: [
      "The loop variable (commonly named `i`) holds the current number in each iteration.",
      "`for i in range(5):` will make `i` go from 0, 1, 2, 3, to 4.",
      "Inside the loop, simply `print(i)` to display the current number.",
    ],
  },
  {
    id: 18,
    topicId: 6,
    topicTitle: "The Spire of Loops",
    isFirstInTopic: false,
    title: "Task 3: A Specific Count",
    description: "Sometimes you need to count within a very specific range.",
    challenge: "Use a `for` loop to print the numbers from 2 up to (but not including) 5.",
    starterCode: "# Your code here\n",
    solution: "for i in range(2, 5):\n    print(i)",
    image: findImage('loop-spire'),
    expectedOutput: "2\n3\n4",
    xp: 50,
    difficulty: 'Medium',
    hints: [
      "The `range()` function can take two arguments: a start and an end.",
      "`range(start, end)` will count from `start` up to `end - 1`.",
      "To get the numbers 2, 3, and 4, you should use `range(2, 5)`."
    ],
  },
  // Topic 7: The Golem's Gauntlet (3 tasks)
  {
    id: 19,
    topicId: 7,
    topicTitle: "The Golem's Gauntlet",
    isFirstInTopic: true,
    title: "Task 1: Odd and Even Stones",
    description: "A golem presents a path of stones, some even, some odd.",
    challenge: "Loop from 1 to 5. If a number is 1, 3, or 5, print 'Odd'. If it's 2 or 4, print 'Even'. (Hint: you will need multiple `if` statements)",
    starterCode: "# Your code here\n",
    solution: "for i in range(1, 6):\n    if i == 1:\n        print('Odd')\n    if i == 2:\n        print('Even')\n    if i == 3:\n        print('Odd')\n    if i == 4:\n        print('Even')\n    if i == 5:\n        print('Odd')",
    image: findImage('golem-gauntlet'),
    expectedOutput: "Odd\nEven\nOdd\nEven\nOdd",
    xp: 50,
    difficulty: 'Medium',
    hints: [
        "You'll need a `for` loop that runs from 1 to 5. `range(1, 6)` will do this.",
        "Inside the loop, you'll need `if` statements to check the value of the loop variable `i`.",
        "Since this simple Python doesn't support advanced math, check each number one-by-one: `if i == 1: ...`, `if i == 2: ...`",
    ],
  },
  {
    id: 20,
    topicId: 7,
    topicTitle: "The Golem's Gauntlet",
    isFirstInTopic: false,
    title: "Task 2: High and Low",
    description: "Sort a sequence of numbers into two groups: 'High' and 'Low'.",
    challenge: "Loop through numbers 1 to 5. If the number is less than 3, print 'Low'. Otherwise, print 'High'.",
    starterCode: "# Your code here\n",
    solution: "for i in range(1, 6):\n    if i < 3:\n        print('Low')\n    else:\n        print('High')",
    image: findImage('golem-gauntlet'),
    expectedOutput: "Low\nLow\nHigh\nHigh\nHigh",
    xp: 55,
    difficulty: 'Hard',
    hints: [
      "Start with a `for` loop using `range(1, 6)`.",
      "Inside the loop, you need an `if/else` statement.",
      "The condition should be `if i < 3:`. This will correctly handle numbers 1 and 2.",
    ],
  },
  {
    id: 21,
    topicId: 7,
    topicTitle: "The Golem's Gauntlet",
    isFirstInTopic: false,
    title: "Task 3: Find the Treasure",
    description: "Search a sequence of chests to find the one with the treasure.",
    challenge: "You are searching in rooms numbered 0 to 4. If you find room number 3, print 'Treasure found!'.",
    starterCode: "# Your code here\n",
    solution: "for i in range(5):\n    if i == 3:\n        print('Treasure found!')",
    image: findImage('golem-gauntlet'),
    expectedOutput: "Treasure found!",
    xp: 60,
    difficulty: 'Hard',
    hints: [
      "Use a `for` loop with `range(5)` to check rooms 0 through 4.",
      "Inside the loop, you only need a single `if` statement. No `else` is needed.",
      "The condition `if i == 3:` will check if you're in the correct room.",
    ],
  },
   // Topic 8: The Alchemist's Lab (3 tasks)
  {
    id: 22,
    topicId: 8,
    topicTitle: "The Alchemist's Lab",
    isFirstInTopic: true,
    title: "Task 1: The Perfect Brew",
    description: "An alchemist needs to mix a potion perfectly. Add ingredients in a sequence.",
    challenge: "Start with a `potion_value` of 0. Loop 5 times. In each loop, add the loop number (0, 1, 2, 3, 4) to `potion_value`. Print the final value after the loop.",
    starterCode: "potion_value = 0\n\n# Your code here\n\nprint(potion_value)",
    solution: "potion_value = 0\nfor i in range(5):\n    potion_value = potion_value + i\nprint(potion_value)",
    image: findImage('alchemists-lab'),
    expectedOutput: "10",
    xp: 60,
    difficulty: 'Hard',
    hints: [
      "Initialize `potion_value = 0` before the loop.",
      "Use a `for` loop that runs 5 times: `for i in range(5):`.",
      "Inside the loop, update the potion value: `potion_value = potion_value + i`.",
      "The final `print` statement should be *after* the loop is finished and not indented.",
    ],
  },
  {
    id: 23,
    topicId: 8,
    topicTitle: "The Alchemist's Lab",
    isFirstInTopic: false,
    title: "Task 2: A Diminishing Draft",
    description: "A potion slowly loses its power over time.",
    challenge: "Start with `power` at 50. Loop 3 times. In each loop, subtract 10 from `power`. Print the final `power` after the loop.",
    starterCode: "power = 50\n\n# Your code here\n\nprint(power)",
    solution: "power = 50\nfor i in range(3):\n    power = power - 10\nprint(power)",
    image: findImage('alchemists-lab'),
    expectedOutput: "20",
    xp: 65,
    difficulty: 'Hard',
    hints: [
      "`power` is already initialized for you.",
      "Use `for i in range(3):` to loop 3 times.",
      "Inside the loop, use the line `power = power - 10` to decrease the value.",
      "The `print(power)` line must be outside the loop to show only the final result."
    ],
  },
  {
    id: 24,
    topicId: 8,
    topicTitle: "The Alchemist's Lab",
    isFirstInTopic: false,
    title: "Task 3: Multiplying Essence",
    description: "A rare essence doubles in potency with each magical incantation.",
    challenge: "Start with `essence` at 1. Loop 4 times. In each loop, double the value of `essence`. Print the final value.",
    starterCode: "essence = 1\n\n# Your code here\n\nprint(essence)",
    solution: "essence = 1\nfor i in range(4):\n    essence = essence * 2\nprint(essence)",
    image: findImage('alchemists-lab'),
    expectedOutput: "16",
    xp: 70,
    difficulty: 'Hard',
    hints: [
      "Use a `for` loop with `range(4)`.",
      "Inside the loop, you need to update `essence` by multiplying it by 2.",
      "The update line should be `essence = essence * 2`.",
      "Make sure you print the `essence` variable *after* the loop has completed."
    ],
  },
   // Topic 9: The Oracle's Chamber (3 tasks)
  {
    id: 25,
    topicId: 9,
    topicTitle: "The Oracle's Chamber",
    isFirstInTopic: true,
    title: "Task 1: The Oracle's Test",
    description: "The Oracle gives a complex riddle that requires careful logic to solve.",
    challenge: "Loop from 1 to 10. If the number is less than 5, print 'low'. If it is greater than 5, print 'high'. If it is exactly 5, print 'middle'.",
    starterCode: "# Your code here\n",
    solution: "for i in range(1, 11):\n    if i < 5:\n        print('low')\n    else:\n        if i > 5:\n            print('high')\n        else:\n            print('middle')",
    image: findImage('oracles-chamber'),
    expectedOutput: "low\nlow\nlow\nlow\nmiddle\nhigh\nhigh\nhigh\nhigh\nhigh",
    xp: 70,
    difficulty: 'Hard',
    hints: [
      "You need a `for` loop that goes from 1 to 10. `range(1, 11)` is what you need.",
      "Inside the loop, use an `if/else` structure. The first `if` can check `i < 5`.",
      "In the `else` block, you'll need another, nested `if/else` to tell the difference between `i > 5` and `i == 5`.",
      "Make sure your indentation is correct for the nested `if` statement."
    ],
  },
  {
    id: 26,
    topicId: 9,
    topicTitle: "The Oracle's Chamber",
    isFirstInTopic: false,
    title: "Task 2: Echoing Halls",
    description: "Create a pattern that echoes through the chamber.",
    challenge: "Use a nested loop. The outer loop should run twice (`range(2)`). The inner loop should run three times (`range(3)`). Inside the inner loop, print 'Echo'.",
    starterCode: "# Your code here\n",
    solution: "for i in range(2):\n    for j in range(3):\n        print('Echo')",
    image: findImage('oracles-chamber'),
    expectedOutput: "Echo\nEcho\nEcho\nEcho\nEcho\nEcho",
    xp: 80,
    difficulty: 'Hard',
    hints: [
      "A nested loop is a loop inside another loop.",
      "Your outer loop can be `for i in range(2):`.",
      "Your inner loop, indented under the outer one, can be `for j in range(3):`.",
      "The `print('Echo')` statement should be indented inside the *inner* loop."
    ],
  },
  {
    id: 27,
    topicId: 9,
    topicTitle: "The Oracle's Chamber",
    isFirstInTopic: false,
    title: "Task 3: The Final Riddle",
    description: "The Oracle's final test combines loops and nested conditions.",
    challenge: "Loop from 1 to 4. If the number is 2, print 'Skip'. If the number is 4, print 'End'. For any other number, print 'Continue'.",
    starterCode: "# Your code here\n",
    solution: "for i in range(1, 5):\n    if i == 2:\n        print('Skip')\n    else:\n        if i == 4:\n            print('End')\n        else:\n            print('Continue')",
    image: findImage('oracles-chamber'),
    expectedOutput: "Continue\nSkip\nContinue\nEnd",
    xp: 90,
    difficulty: 'Hard',
    hints: [
      "Start with a `for` loop using `range(1, 5)`.",
      "The first `if` statement should check `if i == 2:`.",
      "In the `else` block of that first `if`, you'll need a second, nested `if/else` block.",
      "This nested `if/else` will check `if i == 4:` to distinguish between 'End' and 'Continue'.",
    ],
  },
];
