
export type LevelType = 'code' | 'multiple-choice' | 'fill-in-the-blank';

export type BaseLevel = {
  id: number;
  topicId: number;
  topicTitle: string;
  isFirstInTopic: boolean;
  title: string;
  description: string;
  challenge: string;
  xp: number;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  hints: string[];
};

export type CodeLevel = BaseLevel & {
  type: 'code';
  starterCode: string;
  solution: string;
  expectedOutput: string;
};

export type MultipleChoiceLevel = BaseLevel & {
  type: 'multiple-choice';
  choices: string[];
  correctAnswer: number;
  solution: string; // Explanation for the correct answer
};

export type FillInTheBlankLevel = BaseLevel & {
  type: 'fill-in-the-blank';
  starterCode: string; // Code with a blank marker, e.g., "___"
  solution: string; // The word/code that fills the blank
};

export type Level = CodeLevel | MultipleChoiceLevel | FillInTheBlankLevel;

export const levels: Level[] = [
  // Topic 1: Introduction to print() (3 tasks)
  {
    id: 1,
    type: 'code',
    topicId: 1,
    topicTitle: 'Introduction to print()',
    isFirstInTopic: true,
    title: 'Task 1: Hello, World!',
    description: 'Learn how to display messages in Python.',
    challenge: "Use the `print()` function to output the text 'Hello, World!'",
    starterCode: '# Your code here\n',
    solution: "print('Hello, World!')",
    expectedOutput: 'Hello, World!',
    xp: 10,
    difficulty: 'Easy',
    hints: [
      'You need to use a special function to make text appear.',
      "The function you're looking for is `print()`.",
      "Place the text 'Hello, World!' inside the parentheses, wrapped in quotes.",
    ],
  },
  {
    id: 2,
    type: 'multiple-choice',
    topicId: 1,
    topicTitle: 'Introduction to print()',
    isFirstInTopic: false,
    title: 'Task 2: Select the Correct Syntax',
    description: 'Practice your new skill by choosing the correct way to print a message.',
    challenge: "Which of the following is the correct way to print the text 'Python is fun!' to the console?",
    xp: 15,
    difficulty: 'Easy',
    hints: [
      'The function to display text is `print()`.',
      'Text in Python, called a string, needs to be wrapped in quotes.',
      'The string must be placed inside the parentheses of the print function.',
    ],
    choices: [
      "print 'Python is fun!'",
      "console.log('Python is fun!')",
      "print('Python is fun!')",
      "display('Python is fun!')",
    ],
    correctAnswer: 2,
    solution: "The `print()` function requires the text (a 'string') to be enclosed in parentheses and quotation marks.",
  },
  {
    id: 3,
    type: 'fill-in-the-blank',
    topicId: 1,
    topicTitle: 'Introduction to print()',
    isFirstInTopic: false,
    title: 'Task 3: Printing Numbers',
    description: "The `print()` function isn't just for text. It can handle numbers too.",
    challenge: 'Fill in the blank to print the number 100.',
    starterCode: 'print(___)',
    solution: '100',
    xp: 20,
    difficulty: 'Easy',
    hints: [
      'You\'ll use the `print()` function again.',
      "When printing numbers, you don't need to use quotes.",
      'Simply place the number `100` inside the parentheses.',
    ],
  },
  // Topic 2: Variables (3 tasks)
  {
    id: 4,
    type: 'code',
    topicId: 2,
    topicTitle: 'Variables',
    isFirstInTopic: true,
    title: 'Task 1: Storing Text',
    description: 'Learn to store information in variables.',
    challenge: "Create a variable named `message` and set its value to 'First variable'. Then, print the variable.",
    starterCode: '# Create your variable here\n\n# Print your variable here\n',
    solution: "message = 'First variable'\nprint(message)",
    expectedOutput: 'First variable',
    xp: 20,
    difficulty: 'Easy',
    hints: [
      'To create a variable, type the name, an equals sign (`=`), and then the value.',
      "Text values (strings) need to be in quotes, like `'First variable'`.",
      'After creating the variable, use `print(message)` to see its value.',
    ],
  },
  {
    id: 5,
    type: 'fill-in-the-blank',
    topicId: 2,
    topicTitle: 'Variables',
    isFirstInTopic: false,
    title: 'Task 2: Storing Numbers',
    description: 'Variables can also hold numbers. Fill in the blank to complete the code.',
    challenge: 'Create a variable named `score` and set it to `100`.',
    starterCode: 'score = ___',
    solution: '100',
    xp: 25,
    difficulty: 'Easy',
    hints: [
      "You are assigning a value to the variable 'score'.",
      'The value should be the number 100.',
      "Numbers don't need quotes.",
    ],
  },
  {
    id: 6,
    type: 'code',
    topicId: 2,
    topicTitle: 'Variables',
    isFirstInTopic: false,
    title: 'Task 3: Re-assigning a Variable',
    description: "The value of a variable can be changed, or 're-assigned'.",
    challenge: "Create a variable `status` and set it to `'learning'`. Then, on a new line, change its value to `'mastering'`. Finally, print the `status` variable.",
    starterCode: "status = 'learning'\n# Change the status here\n\n# Print the final status\n",
    solution: "status = 'learning'\nstatus = 'mastering'\nprint(status)",
    expectedOutput: 'mastering',
    xp: 30,
    difficulty: 'Medium',
    hints: [
      'The variable `status` is already created for you.',
      "To change its value, simply assign a new value to it on a new line: `status = 'mastering'`.",
      'The final `print()` statement will show the newest value stored in the variable.',
    ],
  },
  // Topic 3: Basic Arithmetic (3 tasks)
  {
    id: 7,
    type: 'multiple-choice',
    topicId: 3,
    topicTitle: 'Basic Arithmetic',
    isFirstInTopic: true,
    title: 'Task 1: Addition',
    description: 'Use Python as a calculator. Start with addition.',
    challenge: "What will `print(120 + 55)` output to the console?",
    choices: ["175", "12055", "'120 + 55'", "Error"],
    correctAnswer: 0,
    solution: "Python performs the addition inside the `print()` function, outputting the sum `175`.",
    xp: 25,
    difficulty: 'Easy',
    hints: [
      'The `print()` function can evaluate mathematical expressions.',
      'The `+` operator performs addition.',
      'The result of the math expression is what gets printed.',
    ],
  },
  {
    id: 8,
    type: 'code',
    topicId: 3,
    topicTitle: 'Basic Arithmetic',
    isFirstInTopic: false,
    title: 'Task 2: Subtraction',
    description: "Now, let's try subtraction.",
    challenge: 'Subtract 65 from 200 and print the result.',
    starterCode: '# Your code here\n',
    solution: 'print(200 - 65)',
    expectedOutput: '135',
    xp: 30,
    difficulty: 'Easy',
    hints: [
      'The operator for subtraction is the minus sign (`-`).',
      'You can perform the calculation directly inside `print()`.\'',
      'Your code should be `print(200 - 65)`.',
    ],
  },
  {
    id: 9,
    type: 'multiple-choice',
    topicId: 3,
    topicTitle: 'Basic Arithmetic',
    isFirstInTopic: false,
    title: 'Task 3: Multiplication Operator',
    description: "Finally, let's practice multiplication.",
    challenge: "Which symbol is used for multiplication in Python?",
    choices: ["x", ".", "*", "&"],
    correctAnswer: 2,
    solution: "The asterisk (`*`) is the multiplication operator in Python.",
    xp: 35,
    difficulty: 'Easy',
    hints: [
      "Different programming languages use different symbols.",
      "In Python, the symbol is one you might see on a calculator keypad.",
      "The correct operator is `*`."
    ],
  },
  // Topic 4: String Manipulation (3 tasks)
  {
    id: 10,
    type: 'multiple-choice',
    topicId: 4,
    topicTitle: 'String Manipulation',
    isFirstInTopic: true,
    title: 'Task 1: String Concatenation',
    description: 'Combine different pieces of text into a single, seamless message.',
    challenge: "What is the result of `print('code' + 'quest')`?",
    choices: ["code quest", "codequest", "Error", "code+quest"],
    correctAnswer: 1,
    solution: "The `+` operator concatenates (joins) strings directly without adding a space.",
    xp: 30,
    difficulty: 'Easy',
    hints: [
      "The `+` operator joins strings end-to-end.",
      "This is called 'concatenation'.",
      "No extra spaces are added automatically.",
    ],
  },
  {
    id: 11,
    type: 'fill-in-the-blank',
    topicId: 4,
    topicTitle: 'String Manipulation',
    isFirstInTopic: false,
    title: 'Task 2: Building a Sentence',
    description: 'Combine three separate words to form a complete thought.',
    challenge: "Fill in the blank to combine `word1`, `word2`, and `word3` to print the phrase 'Coding is fun'.",
    starterCode: "word1 = 'Coding'\nword2 = ' is '\nword3 = 'fun'\n\nprint(word1 + ___ + word3)",
    solution: "word2",
    xp: 35,
    difficulty: 'Medium',
    hints: [
      'You can chain multiple `+` operators together in one line.',
      'To get the full sentence, you need to include the middle part.',
      'The missing variable is `word2`.',
    ],
  },
  {
    id: 12,
    type: 'code',
    topicId: 4,
    topicTitle: 'String Manipulation',
    isFirstInTopic: false,
    title: 'Task 3: Mix and Match',
    description: "Combine a variable with a plain piece of text (a 'string literal').",
    challenge: "A variable `action` holds the word 'Learn'. Combine it with the text ' Python!' and print the result.",
    starterCode: "action = 'Learn'\n\n# Your code here\n",
    solution: "action = 'Learn'\nprint(action + ' Python!')",
    expectedOutput: 'Learn Python!',
    xp: 40,
    difficulty: 'Medium',
    hints: [
      "You can use `+` to add a variable and a string in quotes together.",
      "Make sure to include a space at the beginning of ' Python!' for correct formatting.",
      "Your print statement should be `print(action + ' Python!')`",
    ],
  },
  // Topic 5: Conditional Logic (if/else) (3 tasks)
  {
    id: 13,
    type: 'multiple-choice',
    topicId: 5,
    topicTitle: 'Conditional Logic (if/else)',
    isFirstInTopic: true,
    title: 'Task 1: Conditional Check',
    description: 'Use conditional logic to make decisions in your code.',
    challenge: "If you have a variable `score = 75`, which condition would be true?",
    choices: ["score < 75", "score == 50", "score >= 50", "score != 75"],
    correctAnswer: 2,
    solution: "The condition `score >= 50` is true because 75 is greater than or equal to 50.",
    xp: 35,
    difficulty: 'Easy',
    hints: [
      "Read the operators carefully: `<` is less than, `==` is equal to, `>=` is greater than or equal to, and `!=` is not equal to.",
      "Is 75 less than 75? No.",
      "Is 75 greater than or equal to 50? Yes.",
    ],
  },
  {
    id: 14,
    type: 'fill-in-the-blank',
    topicId: 5,
    topicTitle: 'Conditional Logic (if/else)',
    isFirstInTopic: false,
    title: 'Task 2: Password Check',
    description: 'Check if an input matches an expected value.',
    challenge: "Fill in the blank to check if the `password` variable is equal to the string '1234'.",
    starterCode: "password = '1234'\n\nif password == ___:\n    print('Access granted.')\nelse:\n    print('Access denied.')",
    solution: "'1234'",
    xp: 40,
    difficulty: 'Medium',
    hints: [
      'To check if two values are exactly equal, use a double equals sign (`==`).',
      "You are comparing the `password` variable to a text value.",
      'Text values (strings) must be enclosed in quotes.',
    ],
  },
  {
    id: 15,
    type: 'multiple-choice',
    topicId: 5,
    topicTitle: 'Conditional Logic (if/else)',
    isFirstInTopic: false,
    title: 'Task 3: Age Gate',
    description: 'Control access based on a numerical value.',
    challenge: "Given the code `age = 15`, what will be printed by the conditional `if age > 18: print('Welcome.') else: print('Too young.')`?",
    choices: ["Welcome.", "Too young.", "Error", "Nothing will be printed"],
    correctAnswer: 1,
    solution: "Since the value of `age` (15) is not greater than 18, the condition is false, so the code in the `else` block is executed.",
    xp: 45,
    difficulty: 'Medium',
    hints: [
      "The `if` condition checks if `15 > 18`.",
      "Is 15 greater than 18? No, it is not.",
      "When an `if` condition is false, the `else` block is executed.",
    ],
  },
  // Topic 6: For Loops (3 tasks)
  {
    id: 16,
    type: 'fill-in-the-blank',
    topicId: 6,
    topicTitle: 'For Loops',
    isFirstInTopic: true,
    title: 'Task 1: Simple Repetition',
    description: 'Learn to repeat an action a specific number of times.',
    challenge: "Fill in the blank to create a loop that prints 'Looping' 3 times.",
    starterCode: 'for i in range(___):\n    print(\'Looping\')',
    solution: "3",
    xp: 40,
    difficulty: 'Medium',
    hints: [
      'A `for` loop is used to repeat actions a specific number of times.',
      "Python's `range()` function controls how many times the loop runs.",
      'To run a loop N times, you use `range(N)`.',
    ],
  },
  {
    id: 17,
    type: 'multiple-choice',
    topicId: 6,
    topicTitle: 'For Loops',
    isFirstInTopic: false,
    title: 'Task 2: Understanding `range()`',
    description: 'Use a loop to print a sequence of numbers.',
    challenge: "What sequence of numbers does `range(5)` generate for a `for` loop?",
    choices: ["1, 2, 3, 4, 5", "0, 1, 2, 3, 4, 5", "0, 1, 2, 3, 4", "1, 2, 3, 4"],
    correctAnswer: 2,
    solution: "`range(n)` generates numbers starting from 0 up to, but not including, `n`.",
    xp: 45,
    difficulty: 'Medium',
    hints: [
      "The `range()` function in Python always starts counting from 0 by default.",
      "The sequence stops *before* reaching the number inside the parentheses.",
      "So, `range(5)` gives you 5 numbers, starting from 0.",
    ],
  },
  {
    id: 18,
    type: 'code',
    topicId: 6,
    topicTitle: 'For Loops',
    isFirstInTopic: false,
    title: 'Task 3: A Specific Range',
    description: 'Loops can count within any range you define.',
    challenge: 'Use a `for` loop to print the numbers from 2 up to (but not including) 5.',
    starterCode: '# Your code here\n',
    solution: 'for i in range(2, 5):\n    print(i)',
    expectedOutput: '2\n3\n4',
    xp: 50,
    difficulty: 'Medium',
    hints: [
      'The `range()` function can take two arguments: a start and an end.',
      '`range(start, end)` will count from `start` up to `end - 1`.',
      'To get the numbers 2, 3, and 4, you should use `range(2, 5)`.',
    ],
  },
  // Topic 7: Loops with Conditionals (3 tasks)
  {
    id: 19,
    type: 'code',
    topicId: 7,
    topicTitle: 'Loops with Conditionals',
    isFirstInTopic: true,
    title: 'Task 1: Odd and Even Numbers',
    description: 'Combine loops and conditionals to analyze a sequence of numbers.',
    challenge: "Loop from 1 to 5. If a number is 1, 3, or 5, print 'Odd'. If it's 2 or 4, print 'Even'. (Hint: you will need multiple `if` statements)",
    starterCode: '# Your code here\n',
    solution: "for i in range(1, 6):\n    if i == 1:\n        print('Odd')\n    if i == 2:\n        print('Even')\n    if i == 3:\n        print('Odd')\n    if i == 4:\n        print('Even')\n    if i == 5:\n        print('Odd')",
    expectedOutput: 'Odd\nEven\nOdd\nEven\nOdd',
    xp: 50,
    difficulty: 'Medium',
    hints: [
      'You\'ll need a `for` loop that runs from 1 to 5. `range(1, 6)` will do this.',
      "Inside the loop, you'll need `if` statements to check the value of the loop variable `i`.",
      "Since this simple Python doesn't support advanced math, check each number one-by-one: `if i == 1: ...`, `if i == 2: ...`",
    ],
  },
  {
    id: 20,
    type: 'fill-in-the-blank',
    topicId: 7,
    topicTitle: 'Loops with Conditionals',
    isFirstInTopic: false,
    title: 'Task 2: High and Low',
    description: "Sort a sequence of numbers into two groups: 'High' and 'Low'.",
    challenge: "Fill in the blank. For numbers 1 to 5, if the number is less than 3, print 'Low'. Otherwise, print 'High'.",
    starterCode: "for i in range(1, 6):\n    if i < ___:\n        print('Low')\n    else:\n        print('High')",
    solution: '3',
    xp: 55,
    difficulty: 'Hard',
    hints: [
      'The code is looping from 1 to 5.',
      'The goal is to print "Low" for numbers 1 and 2.',
      'The condition `i < 3` will be true for 1 and 2, and false for 3, 4, and 5.',
    ],
  },
  {
    id: 21,
    type: 'fill-in-the-blank',
    topicId: 7,
    topicTitle: 'Loops with Conditionals',
    isFirstInTopic: false,
    title: 'Task 3: Find a Specific Value',
    description: 'Search a sequence of items to find a specific one.',
    challenge: "Fill in the blank to find room number 3 while searching rooms 0 to 4.",
    starterCode: "for i in range(5):\n    if i == ___:\n        print('Target found!')",
    solution: '3',
    xp: 60,
    difficulty: 'Hard',
    hints: [
      'The loop variable `i` will take on the values 0, 1, 2, 3, and 4.',
      'You need to check when `i` is equal to the target room number.',
      'The target room is 3.',
    ],
  },
  // Topic 8: Updating Variables in Loops (3 tasks)
  {
    id: 22,
    type: 'fill-in-the-blank',
    topicId: 8,
    topicTitle: 'Updating Variables in Loops',
    isFirstInTopic: true,
    title: 'Task 1: Accumulating a Total',
    description: 'Use a loop to calculate a running total.',
    challenge: 'Fill in the blank to add the current loop number to the `total` variable.',
    starterCode: 'total = 0\nfor i in range(5):\n    total = total + ___\nprint(total)',
    solution: 'i',
    xp: 60,
    difficulty: 'Hard',
    hints: [
      'You are trying to accumulate a sum.',
      'In each iteration, you need to add the current value of the loop counter to `total`.',
      'The loop counter variable is named `i`.',
    ],
  },
  {
    id: 23,
    type: 'multiple-choice',
    topicId: 8,
    topicTitle: 'Updating Variables in Loops',
    isFirstInTopic: false,
    title: 'Task 2: Countdown',
    description: 'Use a loop to decrease a value over time.',
    challenge: "What is the final value of `power` after this code runs?\n\npower = 50\nfor i in range(3):\n    power = power - 10\nprint(power)",
    choices: ["50", "30", "20", "0"],
    correctAnswer: 2,
    solution: "The loop runs 3 times. Power starts at 50, then becomes 40, then 30, then 20. The final value is 20.",
    xp: 65,
    difficulty: 'Hard',
    hints: [
      'The loop runs 3 times.',
      'First loop: power becomes 50 - 10 = 40.',
      'Second loop: power becomes 40 - 10 = 30.',
      'Third loop: power becomes 30 - 10 = 20.',
    ],
  },
  {
    id: 24,
    type: 'multiple-choice',
    topicId: 8,
    topicTitle: 'Updating Variables in Loops',
    isFirstInTopic: false,
    title: 'Task 3: Exponential Growth',
    description: 'Model growth that multiplies over time.',
    challenge: "What is the final value of `value` after this code runs?\n\nvalue = 1\nfor i in range(4):\n    value = value * 2\nprint(value)",
    choices: ["4", "8", "16", "32"],
    correctAnswer: 2,
    solution: "The loop runs 4 times. Value starts at 1, then becomes 2, then 4, then 8, then 16. The final value is 16.",
    xp: 70,
    difficulty: 'Hard',
    hints: [
      'The loop runs 4 times.',
      'Start: 1. After 1 loop: 2. After 2 loops: 4.',
      'After 3 loops: 8. After 4 loops: 16.',
    ],
  },
  // Topic 9: Nested Logic and Loops (3 tasks)
  {
    id: 25,
    type: 'code',
    topicId: 9,
    topicTitle: 'Nested Logic and Loops',
    isFirstInTopic: true,
    title: 'Task 1: Complex Sorting',
    description: 'Combine different logical tests to solve a complex problem.',
    challenge: "Loop from 1 to 10. If the number is less than 5, print 'low'. If it is greater than 5, print 'high'. If it is exactly 5, print 'middle'.",
    starterCode: '# Your code here\n',
    solution: "for i in range(1, 11):\n    if i < 5:\n        print('low')\n    else:\n        if i > 5:\n            print('high')\n        else:\n            print('middle')",
    expectedOutput: 'low\nlow\nlow\nlow\nmiddle\nhigh\nhigh\nhigh\nhigh\nhigh',
    xp: 70,
    difficulty: 'Hard',
    hints: [
      'You need a `for` loop that goes from 1 to 10. `range(1, 11)` is what you need.',
      'Inside the loop, use an `if/else` structure. The first `if` can check `i < 5`.',
      'In the `else` block, you\'ll need another, nested `if/else` to tell the difference between `i > 5` and `i == 5`.',
      'Make sure your indentation is correct for the nested `if` statement.',
    ],
  },
  {
    id: 26,
    type: 'fill-in-the-blank',
    topicId: 9,
    topicTitle: 'Nested Logic and Loops',
    isFirstInTopic: false,
    title: 'Task 2: Creating a Pattern',
    description: 'Create a pattern with a loop inside of another loop.',
    challenge: "Fill in the blank to make the inner loop run three times.",
    starterCode: "for i in range(2):\n    for j in range(___):\n        print('Echo')",
    solution: '3',
    xp: 80,
    difficulty: 'Hard',
    hints: [
      'The goal is for the inner loop to run 3 times.',
      '`range(N)` causes a loop to run N times.',
      'So, you need to use `range(3)`.',
    ],
  },
  {
    id: 27,
    type: 'code',
    topicId: 9,
    topicTitle: 'Nested Logic and Loops',
    isFirstInTopic: false,
    title: 'Task 3: The Final Challenge',
    description: 'A final test combining loops and nested conditions.',
    challenge: "Loop from 1 to 4. If the number is 2, print 'Skip'. If the number is 4, print 'End'. For any other number, print 'Continue'.",
    starterCode: '# Your code here\n',
    solution: "for i in range(1, 5):\n    if i == 2:\n        print('Skip')\n    else:\n        if i == 4:\n            print('End')\n        else:\n            print('Continue')",
    expectedOutput: 'Continue\nSkip\nContinue\nEnd',
    xp: 90,
    difficulty: 'Hard',
    hints: [
      'Start with a `for` loop using `range(1, 5)`.',
      "The first `if` statement should check `if i == 2:`. ",
      "In the `else` block of that first `if`, you'll need a second, nested `if/else` block.",
      "This nested `if/else` will check `if i == 4:` to distinguish between 'End' and 'Continue'.",
    ],
  },
];
