'use server';

/**
 * @fileOverview This file defines a Genkit flow for providing debugging assistance to students learning Python.
 *
 * - `provideDebuggingAssistance`: A function that takes code and an error message as input and returns debugging suggestions.
 * - `DebuggingAssistanceInput`: The input type for the `provideDebuggingAssistance` function, including the code and error message.
 * - `DebuggingAssistanceOutput`: The output type for the `provideDebuggingAssistance` function, containing debugging suggestions.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const DebuggingAssistanceInputSchema = z.object({
  code: z.string().describe('The Python code to debug.'),
  errorMessage: z.string().describe('The error message generated by the code.'),
});

export type DebuggingAssistanceInput = z.infer<typeof DebuggingAssistanceInputSchema>;

const DebuggingAssistanceOutputSchema = z.object({
  suggestions: z.array(z.string()).describe('An array of debugging suggestions.'),
});

export type DebuggingAssistanceOutput = z.infer<typeof DebuggingAssistanceOutputSchema>;

export async function provideDebuggingAssistance(
  input: DebuggingAssistanceInput
): Promise<DebuggingAssistanceOutput> {
  return debuggingAssistanceFlow(input);
}

const debuggingAssistancePrompt = ai.definePrompt({
  name: 'debuggingAssistancePrompt',
  input: {schema: DebuggingAssistanceInputSchema},
  output: {schema: DebuggingAssistanceOutputSchema},
  prompt: `You are an AI coding assistant helping a student debug their Python code.
  The student has encountered the following error message:
  """
  {{errorMessage}}
  """
  
  The student's code is:
  """
  {{code}}
  """
  
  Provide a list of debugging suggestions that the student can try to fix the error. Be specific and provide different options if possible.
  Format your response as a JSON array of strings, where each string is a debugging suggestion.
  `,
});

const debuggingAssistanceFlow = ai.defineFlow(
  {
    name: 'debuggingAssistanceFlow',
    inputSchema: DebuggingAssistanceInputSchema,
    outputSchema: DebuggingAssistanceOutputSchema,
  },
  async input => {
    const {output} = await debuggingAssistancePrompt(input);
    return output!;
  }
);
